version: '3.1'
services:
  database:
    container_name: team_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=teamproject'
      - 'POSTGRES_PASSWORD=dcFEEP8xxMf77cJ#'
      - 'POSTGRES_USER=january'
    ports:
      - '5432:5432'
  backend:
    container_name: dotnet_backend
    build: ./
    ports:
      - '7088:7088'
      - '5169:5169'
    volumes:
      - ./Controllers:/app/Controllers
      - ./Model:/app/Model
      - ./Program.cs:/app/Program.cs
      - ./ClientApp/src:/app/ClientApp/src
    depends_on:
      - database
  frontend:
    container_name: dotnet_frontend
    build: ./ClientApp
    depends_on:
      - backend
    ports:
      - '44485:44485'
    volumes:
      - ./ClientApp/src:/app/src
