FROM node:20.11.1

ENV DOCKER_HOST=host.docker.internal

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npx update-browserslist-db@latest

COPY . .

EXPOSE 44485

CMD [ "npm", "run", "docker-run" ]